# Generated by Django 3.0.7 on 2021-07-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210713_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='ceated_date',
            new_name='created_date',
        ),
    ]
